# -*- coding: utf-8 -*-
"""task1cifar10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OemWhYFAbtIZH6YZTPxLl4XfL16S1Xss
"""

import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import transforms
from torchvision.transforms import ToTensor
from torch import optim
from torchvision import datasets

train_transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2470, 0.2435, 0.2616))
])

test_transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2470, 0.2435, 0.2616))
])

train_data = datasets.CIFAR10(
    root = "data",
    train = True,
    download = True,
    transform = train_transform
)

test_data = datasets.CIFAR10(
    root = "data",
    train = False,
    download = True,
    transform = test_transform
)

batch = 128

train_dataloader = DataLoader(train_data, batch_size = batch)
test_dataloader = DataLoader(test_data, batch_size = batch)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

import torch

def check_cuda():
    print("Torch Version:", torch.__version__)
    if torch.cuda.is_available():
        print("CUDA is available")
        print("GPU Name:", torch.cuda.get_device_name(0))
    else:
        print("CUDA is not available")


check_cuda()

class CNN(nn.Module):
    def __init__(self):
        super(self).__init__()
        self.model = nn.Sequential(
            nn.Conv2d(3, 32, 3),  # Output: (32, 30, 30)
            nn.ReLU(),
            nn.Conv2d(32, 64, 3),  # Output: (64, 28, 28)
            nn.ReLU(),
            nn.MaxPool2d(2),  # Output: (64, 14, 14)
            nn.Conv2d(64, 128, 3),  # Output: (128, 12, 12)
            nn.ReLU(),
            nn.MaxPool2d(2),  # Output: (128, 6, 6)
            nn.Flatten(),  # Output: (128 * 6 * 6) = (4608)
            nn.Linear(128 * 6 * 6, 256), # Correct input size of 4608!
            nn.Dropout(0.5),
            nn.Linear(256, 64),
            nn.Linear(64, 10)
        )

    def forward(self, x):
        return self.model(x)

model = CNN().to(device)

loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)

def train(train_dataloader, model, loss_fn, optimizer):
    size = len(train_dataloader.dataset)
    model.train()
    for batch, (X, y) in enumerate(train_dataloader):
        X, y = X.to(device), y.to(device)

        # Compute prediction error
        pred = model(X)
        loss = loss_fn(pred, y)

        # Backpropagation
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()

        if batch % 100 == 0:
            loss, current = loss.item(), (batch + 1) * len(X)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")

def test(train_dataloader, model, loss_fn):
    size = len(train_dataloader.dataset)
    num_batches = len(train_dataloader)
    model.eval()
    test_loss, correct = 0, 0
    with torch.no_grad():
        for X, y in train_dataloader:
            X, y = X.to(device), y.to(device)
            pred = model(X)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()
    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")

epochs = 5
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train(train_dataloader, model, loss_fn, optimizer)
    test(test_dataloader, model, loss_fn)
print("Done!")